# Generated by Django 4.2.29 on 2026-03-26 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0045_billing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('role', models.CharField(choices=[('gutachter', 'Gutachter (Verkehrswertgutachten)'), ('makler', 'Makler (Exposé)')], max_length=20, verbose_name='Rolle')),
                ('file', models.FileField(upload_to='description_templates/', verbose_name='Datei (PDF oder TXT)')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Extrahierter Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Beschreibungsvorlage',
                'verbose_name_plural': 'Beschreibungsvorlagen',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('role', models.CharField(choices=[('gutachter', 'Gutachter (Verkehrswertgutachten)'), ('makler', 'Makler (Exposé)')], max_length=20, verbose_name='Rolle')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Straße + Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('building_type', models.CharField(blank=True, max_length=100, verbose_name='Gebäudeart')),
                ('year_of_construction', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baujahr')),
                ('living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Wohnfläche (m²)')),
                ('plot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Grundstücksfläche (m²)')),
                ('number_of_rooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Zimmeranzahl')),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stockwerke')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Zustand')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Zusätzliche Hinweise für die KI')),
                ('generated_text', models.TextField(blank=True, verbose_name='Generierter Text')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generiert am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reports', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reports', to='crm.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Baubeschreibung',
                'verbose_name_plural': 'Baubeschreibungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('photo', 'Fotos'), ('plan', 'Grundrisse / Pläne'), ('bauakte', 'Bauakte / Beschreibungen'), ('misc', 'Sonstige Dokumente')], max_length=20, verbose_name='Dateityp')),
                ('file', models.FileField(upload_to='property_reports/%Y/%m/', verbose_name='Datei')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Bezeichnung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='proptech.propertyreport')),
            ],
            options={
                'ordering': ['file_type', 'uploaded_at'],
            },
        ),
    ]
