# Generated by Django 4.2.29 on 2026-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proptech', '0002_markdown_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiontemplate',
            name='building_type',
            field=models.CharField(blank=True, choices=[('efh', 'Einfamilienhaus'), ('dh', 'Doppelhaushälfte / Reihenhaus'), ('mfh', 'Mehrfamilienhaus'), ('etw', 'Eigentumswohnung'), ('gewerbe', 'Gewerbeimmobilie'), ('sonstige', 'Sonstige')], max_length=20, verbose_name='Gebäudetyp'),
        ),
    ]
