# Generated by Django 4.2.29 on 2026-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proptech', '0003_template_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptiontemplate',
            name='building_type',
            field=models.CharField(blank=True, choices=[('efh', 'Einfamilienhaus'), ('zfh', 'Zweifamilienhaus'), ('dh', 'Doppelhaushälfte / Reihenhaus'), ('mfh', 'Mehrfamilienhaus'), ('etw', 'Eigentumswohnung'), ('bauplatz', 'Bauplatz / Grundstück'), ('gewerbe', 'Gewerbeimmobilie'), ('sonstige', 'Sonstige')], max_length=20, verbose_name='Gebäudetyp'),
        ),
    ]
