# Generated by Django 4.2.29 on 2026-03-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proptech', '0005_report_building_type_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiontemplate',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='descriptiontemplate',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='descriptiontemplate',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Straße + Hausnummer'),
        ),
    ]
