# Generated by Django 4.2.29 on 2026-03-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proptech', '0006_template_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreportfile',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Fotos'), ('plan', 'Grundrisse / Pläne'), ('bauakte', 'Bauakte / Beschreibungen'), ('energieausweis', 'Energieausweis'), ('misc', 'Sonstige Dokumente')], max_length=20, verbose_name='Dateityp'),
        ),
    ]
