# Generated by Django 4.2.29 on 2026-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proptech', '0007_add_energieausweis_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreportfile',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Fotos'), ('plan', 'Grundrisse / Pläne'), ('flaechenberechnung', 'Flächenberechnung'), ('baubeschreibung_original', 'Baubeschreibung (original)'), ('bauakte', 'Bauakte'), ('energieausweis', 'Energieausweis'), ('grundbuch', 'Grundbuch und Auskünfte'), ('misc', 'Sonstige Dokumente')], max_length=30, verbose_name='Dateityp'),
        ),
    ]
