# Generated by Django 4.2.29 on 2026-03-08 11:28

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('team_lead', 'Teamleiter'), ('employee', 'Mitarbeiter')], default='employee', max_length=20, verbose_name='Rolle')),
                ('totp_secret', models.CharField(blank=True, help_text='Base32-kodiertes Secret für TOTP-Authenticator-Apps.', max_length=64, verbose_name='TOTP-Secret')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='TOTP aktiviert')),
                ('notify_by_email', models.BooleanField(default=True, verbose_name='E-Mail-Benachrichtigungen')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('invoice_created', 'Rechnung erstellt'), ('invoice_paid', 'Rechnung bezahlt'), ('offer_created', 'Angebot erstellt'), ('budget_warning', 'Budget-Warnung (80 %)'), ('budget_exceeded', 'Budget überschritten'), ('time_entry_submitted', 'Stunden eingereicht'), ('time_entry_approved', 'Stunden freigegeben'), ('time_entry_rejected', 'Stunden abgelehnt'), ('project_status_change', 'Projektstatus geändert')], max_length=50, verbose_name='Ereignis')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('body', models.TextField(verbose_name='Inhalt')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('context_payload', models.JSONField(blank=True, default=dict, verbose_name='Kontext-Payload')),
            ],
            options={
                'verbose_name': 'Benachrichtigungs-Log',
                'verbose_name_plural': 'Benachrichtigungs-Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('invoice_created', 'Rechnung erstellt'), ('invoice_paid', 'Rechnung bezahlt'), ('offer_created', 'Angebot erstellt'), ('budget_warning', 'Budget-Warnung (80 %)'), ('budget_exceeded', 'Budget überschritten'), ('time_entry_submitted', 'Stunden eingereicht'), ('time_entry_approved', 'Stunden freigegeben'), ('time_entry_rejected', 'Stunden abgelehnt'), ('project_status_change', 'Projektstatus geändert')], max_length=50, verbose_name='Ereignis')),
            ],
            options={
                'verbose_name': 'Benachrichtigungs-Abonnement',
                'verbose_name_plural': 'Benachrichtigungs-Abonnements',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('invoice_created', 'Rechnung erstellt'), ('invoice_paid', 'Rechnung bezahlt'), ('offer_created', 'Angebot erstellt'), ('budget_warning', 'Budget-Warnung (80 %)'), ('budget_exceeded', 'Budget überschritten'), ('time_entry_submitted', 'Stunden eingereicht'), ('time_entry_approved', 'Stunden freigegeben'), ('time_entry_rejected', 'Stunden abgelehnt'), ('project_status_change', 'Projektstatus geändert')], max_length=50, unique=True, verbose_name='Ereignis')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('body_template', models.TextField(help_text='Django-Template-Syntax. Verfügbare Variablen hängen vom Ereignis ab, z.B. {{ project.name }}, {{ invoice.amount }}.', verbose_name='Nachrichtenvorlage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Benachrichtigungsvorlage',
                'verbose_name_plural': 'Benachrichtigungsvorlagen',
            },
        ),
    ]
