# Generated by Django 4.2.29 on 2026-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Einladung gesendet am'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Einladungs-Token'),
        ),
    ]
