# Generated by Django 4.2.29 on 2026-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_invitation_sent_at_user_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('project_manager', 'Projektleiter'), ('employee', 'Mitarbeiter'), ('project_assistant', 'Projektassistenz')], default='employee', max_length=30, verbose_name='Rolle'),
        ),
    ]
