# Generated by Django 4.2.29 on 2026-03-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('contact_role', 'Kontaktrolle'), ('project_type', 'Projekttyp'), ('company', 'Unternehmen')], max_length=30, verbose_name='Kategorie')),
                ('label', models.CharField(help_text="Angezeigter Text im Dropdown, z.B. 'Architekt'", max_length=100, verbose_name='Bezeichnung')),
                ('value', models.CharField(help_text="Interner Schlüssel, z.B. 'architect'. Kleinbuchstaben, keine Leerzeichen.", max_length=50, verbose_name='Wert')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Auswahloption',
                'verbose_name_plural': 'Auswahloptionen',
                'ordering': ['category', 'order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
