# Generated by Django 4.2.29 on 2026-03-10 23:29

from django.db import migrations


CONTACT_ROLES = [
    ("architect",   "Architekt",           0),
    ("authority",   "Behörde",             1),
    ("bank",        "Bank / Finanzierer",  2),
    ("broker",      "Makler",              3),
    ("buyer",       "Käufer",              4),
    ("lawyer",      "Anwalt",              5),
    ("notary",      "Notar",               6),
    ("pm",          "Projektentwickler",   7),
    ("seller",      "Verkäufer",           8),
    ("tax_advisor", "Steuerberater",       9),
    ("other",       "Sonstiges",           10),
]

PROJECT_TYPES = [
    ("consulting",         "Beratung",            0),
    ("developer",          "Erschließungsträger", 1),
    ("appraisal",          "Gutachten",           2),
    ("platform",           "Plattform",           3),
    ("project_management", "Projektmanagement",   4),
    ("scan",               "Scan",                5),
    ("sale",               "Verkauf",             6),
    ("rental",             "Vermietung",          7),
]

COMPANIES = [
    ("direso",     "DIRESO",     0),
    ("gt_immo",    "GT Immo",    1),
    ("gt_projekt", "GT Projekt", 2),
]


def populate_lookups(apps, schema_editor):
    Lookup = apps.get_model("core", "Lookup")
    entries = []
    for value, label, order in CONTACT_ROLES:
        entries.append(Lookup(category="contact_role", value=value, label=label, order=order))
    for value, label, order in PROJECT_TYPES:
        entries.append(Lookup(category="project_type", value=value, label=label, order=order))
    for value, label, order in COMPANIES:
        entries.append(Lookup(category="company", value=value, label=label, order=order))
    Lookup.objects.bulk_create(entries, ignore_conflicts=True)


def remove_lookups(apps, schema_editor):
    Lookup = apps.get_model("core", "Lookup")
    Lookup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_lookup_model"),
    ]

    operations = [
        migrations.RunPython(populate_lookups, remove_lookups),
    ]
