# Generated by Django 4.2.29 on 2026-03-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_lookup_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('project_manager', 'Projektleiter'), ('employee', 'Mitarbeiter'), ('project_assistant', 'Projektassistenz')], max_length=30, unique=True, verbose_name='Rolle')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stundensatz (€ netto)')),
            ],
            options={
                'verbose_name': 'Rollen-Stundensatz',
                'verbose_name_plural': 'Rollen-Stundensätze',
                'ordering': ['role'],
            },
        ),
        migrations.AlterField(
            model_name='lookup',
            name='category',
            field=models.CharField(choices=[('contact_role', 'Kontaktrolle'), ('project_type', 'Projekttyp'), ('company', 'Unternehmen'), ('user_role', 'Benutzerrolle')], max_length=30, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='employee', max_length=30, verbose_name='Rolle'),
        ),
    ]
