# Generated by Django 4.2.29 on 2026-03-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_role_rates_and_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='E-Mail-MFA aktiviert'),
        ),
        migrations.CreateModel(
            name='EmailOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('expires_at', models.DateTimeField(verbose_name='Läuft ab am')),
                ('used', models.BooleanField(default=False, verbose_name='Verwendet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'E-Mail-OTP-Code',
                'verbose_name_plural': 'E-Mail-OTP-Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
