# Generated by Django 4.2.29 on 2026-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_email_mfa_enabled_emailotpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='color',
            field=models.CharField(blank=True, help_text="Optionale Markenfarbe, z.B. '#1B70BF'. Wird u.a. im Dashboard verwendet.", max_length=7, verbose_name='Farbe (Hex)'),
        ),
    ]
