# Generated by Django 4.2.29 on 2026-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lookup_color_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text="Interner Wert aus dem Lookup 'company', z.B. 'gt_immo'.", max_length=50, unique=True, verbose_name='Unternehmen')),
                ('lexoffice_api_key', models.CharField(blank=True, help_text='Persönlicher API-Schlüssel aus dem jeweiligen Lexoffice-Konto.', max_length=255, verbose_name='Lexoffice API-Key')),
            ],
            options={
                'verbose_name': 'Firmen-Zugangsdaten',
                'verbose_name_plural': 'Firmen-Zugangsdaten',
                'ordering': ['company'],
            },
        ),
    ]
