# Generated by Django 4.2.29 on 2026-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255, verbose_name='Firmenname')),
                ('legal_form', models.CharField(blank=True, max_length=100, verbose_name='Rechtsform')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Straße + Nr.')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Land')),
                ('hrb_number', models.CharField(blank=True, max_length=100, verbose_name='HRB-Nummer')),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='Umsatzsteuer-ID')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Bankname')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('pdf_footer_text', models.TextField(blank=True, verbose_name='PDF-Fußzeile')),
                ('payment_days', models.PositiveSmallIntegerField(default=14, verbose_name='Zahlungsziel (Tage)')),
                ('primary_color', models.CharField(default='#1666b0', max_length=7, verbose_name='Primärfarbe (Hex)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmeneinstellungen',
                'verbose_name_plural': 'Firmeneinstellungen',
            },
        ),
    ]
