# Generated by Django 4.2.29 on 2026-03-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_required',
            field=models.BooleanField(default=True, help_text='Wenn aktiv, muss der User beim Login einen TOTP-Code eingeben. Nur vom Admin steuerbar.', verbose_name='2FA Pflicht'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Wird automatisch gesetzt sobald der User den QR-Code bestätigt hat.', verbose_name='TOTP eingerichtet'),
        ),
    ]
