# Generated by Django 4.2.29 on 2026-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_totp_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='registry_court',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registergericht (Amtsgericht)'),
        ),
    ]
