# Generated by Django 4.2.29 on 2026-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_companysettings_registry_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank2_bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='Bank 2 – BIC'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank2_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='Bank 2 – IBAN'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank2_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank 2 – Name'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='geschaeftsfuehrer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Geschäftsführer'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank 1 – Name'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='Bank 1 – BIC'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='Bank 1 – IBAN'),
        ),
    ]
