# Generated by Django 4.2.29 on 2026-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_update_primary_color_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='primary_color',
            field=models.CharField(default='#2F6FB3', max_length=7, verbose_name='Primärfarbe (Hex)'),
        ),
    ]
