# Generated by Django 4.2.29 on 2026-03-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_companysettings_primary_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyCredential',
        ),
        migrations.DeleteModel(
            name='Lookup',
        ),
    ]
