# Generated by Django 4.2.29 on 2026-03-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_lookup_and_company_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text="Interner Schlüssel, z.B. 'admin' oder 'projektleiter'", unique=True, verbose_name='Kürzel')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Stundensatz (€)')),
                ('is_protected', models.BooleanField(default=False, help_text='Geschützte Rollen können nicht gelöscht werden', verbose_name='Geschützt')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Benutzerrolle',
                'verbose_name_plural': 'Benutzerrollen',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='RoleHourlyRate',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='employee', max_length=50, verbose_name='Rolle'),
        ),
    ]
