# Generated by Django 4.2.29 on 2026-03-08 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('account_type', models.CharField(choices=[('customer', 'Kunde'), ('internal', 'Intern'), ('partner', 'Partner')], default='customer', max_length=20, verbose_name='Typ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Adresszeile 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Adresszeile 2')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Land')),
                ('lexoffice_id', models.CharField(blank=True, help_text='UUID des Kontakts in Lexoffice. Wird für API-Sync benötigt.', max_length=100, verbose_name='Lexoffice-ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Account-Manager')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Projektname')),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('offer_sent', 'Angebot versendet'), ('active', 'Aktiv'), ('on_hold', 'Pausiert'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='lead', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('budget_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Budget (Stunden)')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget (€)')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stundensatz (€)')),
                ('storage_path', models.CharField(blank=True, help_text="Absoluter oder relativer Pfad zum Projektordner auf dem Netzlaufwerk bzw. Azure Blob Storage Container-Pfad. Beispiele: '\\\\srv01\\projekte\\2024\\Kunde-X' oder 'projects/2024/kunde-x' (Azure Blob).", max_length=1024, verbose_name='Speicherpfad')),
                ('lexoffice_id', models.CharField(blank=True, help_text='UUID des zugehörigen Projekts / Vorgangs in Lexoffice.', max_length=100, verbose_name='Lexoffice-ID')),
                ('internal_reference', models.CharField(blank=True, max_length=100, verbose_name='Interne Referenz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.account', verbose_name='Account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('team_lead', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['team_lead', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Projektleiter')),
                ('team_members', models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Team-Mitglieder')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('offer', 'Angebot'), ('invoice', 'Rechnung'), ('contract', 'Vertrag'), ('delivery', 'Lieferschein'), ('misc', 'Sonstiges')], max_length=20, verbose_name='Dokumententyp')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('file_path', models.CharField(help_text="Vollständiger Pfad zur Datei auf dem Netzlaufwerk oder Azure Blob Storage Key. Beispiel: '\\\\srv01\\projekte\\2024\\KundeX\\Angebot_001.pdf'", max_length=1024, verbose_name='Dateipfad')),
                ('lexoffice_id', models.CharField(blank=True, help_text='ID des Belegs in Lexoffice (bei Rechnungen und Angeboten).', max_length=100, verbose_name='Lexoffice-ID')),
                ('lexoffice_document_number', models.CharField(blank=True, help_text="Lesbare Belegnummer aus Lexoffice, z.B. 'RE-2024-0042'.", max_length=50, verbose_name='Belegnummer (Lexoffice)')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nettobetrag (€)')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bruttobetrag (€)')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Belegdatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeitsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.project', verbose_name='Projekt')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Eingetragen von')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
    ]
