# Generated by Django 4.2.29 on 2026-03-08 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, help_text='Wird automatisch vergeben, z.B. KD-00001', max_length=20, unique=True, verbose_name='Kundennummer'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, help_text='Wird automatisch vergeben, z.B. PRJ-00001', max_length=20, unique=True, verbose_name='Projektnummer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['project_manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Projektleiter'),
        ),
    ]
