# Generated by Django 4.2.29 on 2026-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_account_account_number_project_project_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('consulting', 'Beratung'), ('appraisal', 'Gutachten'), ('platform', 'Plattform'), ('scan', 'Scan'), ('sale', 'Verkauf'), ('rental', 'Vermietung')], default='consulting', max_length=20, verbose_name='Projekttyp'),
        ),
    ]
