# Generated by Django 4.2.29 on 2026-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('offer_sent', 'Angebot versendet'), ('active', 'Aktiv'), ('on_hold', 'Pausiert'), ('invoiced', 'Rechnung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='lead', max_length=20, verbose_name='Status'),
        ),
    ]
