# Generated by Django 4.2.29 on 2026-03-08 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMemberRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stundensatz (€ netto)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_rates', to='crm.project', verbose_name='Projekt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_rates', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Projektmitglied-Stundensatz',
                'verbose_name_plural': 'Projektmitglied-Stundensätze',
                'ordering': ['user__last_name', 'user__first_name'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
