# Generated by Django 4.2.29 on 2026-03-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_project_member_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudgetExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag (€ netto)')),
                ('approved_at', models.DateField(verbose_name='Freigabedatum')),
                ('note', models.TextField(blank=True, verbose_name='Anmerkung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_extensions', to='crm.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Budget-Erweiterung',
                'verbose_name_plural': 'Budget-Erweiterungen',
                'ordering': ['approved_at'],
            },
        ),
    ]
