# Generated by Django 4.2.29 on 2026-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_project_budget_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, choices=[('direso', 'DIRESO'), ('gt_immo', 'GT Immo'), ('gt_projekt', 'GT Projekt')], default='', max_length=20, verbose_name='Unternehmen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('consulting', 'Beratung'), ('developer', 'Erschließungsträger'), ('appraisal', 'Gutachten'), ('platform', 'Plattform'), ('project_management', 'Projektmanagement'), ('scan', 'Scan'), ('sale', 'Verkauf'), ('rental', 'Vermietung')], default='consulting', max_length=20, verbose_name='Projekttyp'),
        ),
    ]
