# Generated by Django 4.2.29 on 2026-03-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_add_company_and_project_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commission_inner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Innenprovision (% netto)'),
        ),
        migrations.AddField(
            model_name='project',
            name='commission_outer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Außenprovision (% netto)'),
        ),
        migrations.AddField(
            model_name='project',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Notarieller Kaufpreis in EUR (Basis für Provisionsberechnung).', max_digits=14, null=True, verbose_name='Not. Kaufpreis (€)'),
        ),
    ]
