# Generated by Django 4.2.29 on 2026-03-08 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_add_sale_commission_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Firma')),
                ('role', models.CharField(blank=True, choices=[('architect', 'Architekt'), ('authority', 'Behörde'), ('bank', 'Bank / Finanzierer'), ('broker', 'Makler'), ('buyer', 'Käufer'), ('lawyer', 'Anwalt'), ('notary', 'Notar'), ('pm', 'Projektentwickler'), ('seller', 'Verkäufer'), ('tax_advisor', 'Steuerberater'), ('other', 'Sonstiges')], max_length=20, verbose_name='Rolle')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobil')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Straße / Nr.')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Land')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='contacts', to='crm.account', verbose_name='Accounts')),
                ('projects', models.ManyToManyField(blank=True, related_name='contacts', to='crm.project', verbose_name='Projekte')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_accounts', to='crm.contact', verbose_name='Ansprechpartner'),
        ),
    ]
