# Generated by Django 4.2.29 on 2026-03-08 21:14

from django.db import migrations, models


def remap_account_types(apps, schema_editor):
    Account = apps.get_model("crm", "Account")
    Account.objects.filter(account_type="customer").update(account_type="company")
    Account.objects.filter(account_type="partner").update(account_type="company")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_contact_model'),
    ]

    operations = [
        migrations.RunPython(remap_account_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('private', 'Privatperson'), ('company', 'Unternehmen'), ('estate', 'Erbengemeinschaft'), ('internal', 'Intern')], default='company', max_length=20, verbose_name='Typ'),
        ),
    ]
