# Generated by Django 4.2.29 on 2026-03-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_update_account_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Empfängeradresse für den automatischen Rechnungsversand', max_length=254, verbose_name='Rechnungs-E-Mail'),
        ),
    ]
