# Generated by Django 4.2.29 on 2026-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_document_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='predecessor_projects',
            field=models.ManyToManyField(blank=True, related_name='successor_projects', to='crm.project', verbose_name='Vorgängerprojekte'),
        ),
    ]
