# Generated by Django 4.2.29 on 2026-03-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_project_account_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Unternehmen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='consulting', max_length=20, verbose_name='Projekttyp'),
        ),
    ]
