# Generated by Django 4.2.29 on 2026-03-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_choices_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProjectTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text="Interner Wert des Unternehmens, z.B. 'gt_immo'.", max_length=50, verbose_name='Unternehmen')),
                ('project_type', models.CharField(help_text="Interner Wert des Projekttyps, z.B. 'consulting'.", max_length=50, verbose_name='Projekttyp')),
            ],
            options={
                'verbose_name': 'Projekttyp-Zuweisung',
                'verbose_name_plural': 'Projekttyp-Zuweisungen',
                'ordering': ['company', 'project_type'],
                'unique_together': {('company', 'project_type')},
            },
        ),
    ]
