# Generated by Django 4.2.29 on 2026-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_populate_company_project_type_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text="Interner Wert, z.B. 'gt_immo'.", max_length=50, verbose_name='Unternehmen')),
                ('year', models.IntegerField(verbose_name='Jahr')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jahresziel (€ netto)')),
            ],
            options={
                'verbose_name': 'Umsatzziel',
                'verbose_name_plural': 'Umsatzziele',
                'ordering': ['-year', 'company'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
