# Generated by Django 4.2.29 on 2026-03-13 14:39

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0019_revenue_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('accepted', 'Beauftragt'), ('rejected', 'Abgelehnt')], default='draft', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('intro_text', models.TextField(blank=True, verbose_name='Einleitungstext')),
                ('closing_text', models.TextField(blank=True, verbose_name='Schlusstext')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='MwSt. (%)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('offer_date', models.DateField(default=datetime.date.today, verbose_name='Angebotsdatum')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Empfänger Name')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Empfänger E-Mail')),
                ('recipient_address', models.TextField(blank=True, verbose_name='Empfänger Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='crm.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['-offer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('call', 'Telefonat'), ('meeting', 'Meeting'), ('email', 'E-Mail-Verweis'), ('note', 'Notiz'), ('document', 'Dokument')], max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('body', models.TextField(blank=True, verbose_name='Inhalt')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='activity_attachments/', verbose_name='Dateianhang')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum / Uhrzeit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.project')),
            ],
            options={
                'verbose_name': 'Projektaktivität',
                'verbose_name_plural': 'Projektaktivitäten',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='Position')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, verbose_name='Menge')),
                ('unit', models.CharField(blank=True, default='pauschal', max_length=50, verbose_name='Einheit')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Einzelpreis (€ netto)')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.offer', verbose_name='Angebot')),
            ],
            options={
                'verbose_name': 'Angebotsposition',
                'verbose_name_plural': 'Angebotspositionen',
                'ordering': ['position'],
            },
        ),
    ]
