# Generated by Django 4.2.29 on 2026-03-15 16:49

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0020_offer_projectactivity_offeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('invoice_type', models.CharField(choices=[('standard', 'Standardrechnung'), ('partial', 'Abschlagsrechnung'), ('final', 'Schlussrechnung')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=20)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('closing_text', models.TextField(blank=True)),
                ('payment_info', models.TextField(blank=True, help_text='IBAN, BIC, Verwendungszweck')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_address', models.TextField(blank=True)),
                ('net_total_cached', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='is_order_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
                ('unit', models.CharField(blank=True, default='pauschal', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoice')),
            ],
            options={
                'verbose_name': 'Rechnungsposition',
                'verbose_name_plural': 'Rechnungspositionen',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.offer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.project'),
        ),
    ]
