# Generated by Django 4.2.29 on 2026-03-15 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_invoice_offer_is_order_confirmation_invoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('unit', models.CharField(default='pauschal', max_length=50, verbose_name='Einheit')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, verbose_name='Menge')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Einzelpreis (Netto)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produkt / Dienstleistung',
                'verbose_name_plural': 'Produktkatalog',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
