# Generated by Django 4.2.29 on 2026-03-15 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_productcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('submitted', 'Eingereicht'), ('imported', 'Übernommen')], default='pending', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nachname')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Firma')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Straße + Nr.')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('request_description', models.TextField(blank=True, verbose_name='Beschreibung des Anliegens')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_inquiry', to='crm.project')),
            ],
            options={
                'verbose_name': 'Lead-Anfrage',
                'verbose_name_plural': 'Lead-Anfragen',
            },
        ),
    ]
