# Generated by Django 4.2.29 on 2026-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_leadinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinquiry',
            name='customer_type',
            field=models.CharField(choices=[('private', 'Privatperson'), ('company', 'Unternehmen')], default='private', max_length=10, verbose_name='Kundentyp'),
        ),
    ]
