# Generated by Django 4.2.29 on 2026-03-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_leadinquiry_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinquiry',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Rechnungs-E-Mail'),
        ),
    ]
