# Generated by Django 4.2.29 on 2026-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_leadinquiry_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='offer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
    ]
