# Generated by Django 4.2.29 on 2026-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_softdelete_account_project_offer_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='payment_terms',
            field=models.TextField(blank=True, verbose_name='Zahlungsbedingung'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='closing_text',
            field=models.TextField(blank=True, verbose_name='Nachbemerkung'),
        ),
    ]
