# Generated by Django 4.2.29 on 2026-03-15 21:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_offer_payment_terms_companysettings_banking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='Umsatzsteuer (%)'),
        ),
    ]
