# Generated by Django 4.2.29 on 2026-03-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_offer_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.project'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='crm.project', verbose_name='Projekt'),
        ),
    ]
