# Generated by Django 4.2.29 on 2026-03-24 13:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_offer_invoice_project_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(choices=[('intro', 'Einleitungstext'), ('closing', 'Nachbemerkung'), ('payment', 'Zahlungsbedingung'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kategorie')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Textbaustein',
                'verbose_name_plural': 'Textbausteine',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_kleinunternehmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('optional', 'Optional'), ('text', 'Freitext')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Gesamtrabatt (%)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_kleinunternehmer',
            field=models.BooleanField(default=False, verbose_name='Kleinunternehmer (§19 UStG)'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Rabatt (%)'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='item_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('optional', 'Optional'), ('text', 'Freitext')], default='normal', max_length=10, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Einzelpreis (€ netto)'),
        ),
    ]
