# Generated by Django 4.2.29 on 2026-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_offer_invoice_items_textblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Einheit')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gesamtrabatt (€)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('normal', 'Standard'), ('optional', 'Optional'), ('text', 'Freitext')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='item_type',
            field=models.CharField(choices=[('normal', 'Standard'), ('optional', 'Optional'), ('text', 'Freitext')], default='normal', max_length=10, verbose_name='Typ'),
        ),
    ]
