# Generated by Django 4.2.29 on 2026-03-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_offeritem_title_invoiceitem_title'),
    ]

    operations = [
        # 1. Create new standalone ProjectType model
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#2F6FB3', max_length=7, verbose_name='Farbe')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Projekttyp',
                'verbose_name_plural': 'Projekttypen',
                'ordering': ['order', 'name'],
            },
        ),
        # 2. Remove CompanyProjectTypeMapping
        migrations.DeleteModel(
            name='CompanyProjectTypeMapping',
        ),
        # 3. Rename the old CharField to project_type_old to preserve data
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='project_type_old',
        ),
        # 4. Add new project_type FK (null=True so existing rows are fine)
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='crm.projecttype',
                verbose_name='Projekttyp',
            ),
        ),
    ]
