# Generated by Django 4.2.29 on 2026-03-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_remove_project_type_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
    ]
