# Generated by Django 4.2.29 on 2026-03-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_remove_company_and_contact_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenuetarget',
            options={'ordering': ['-year'], 'verbose_name': 'Umsatzziel', 'verbose_name_plural': 'Umsatzziele'},
        ),
        migrations.AlterUniqueTogether(
            name='revenuetarget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='revenuetarget',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='Jahr'),
        ),
        migrations.RemoveField(
            model_name='revenuetarget',
            name='company',
        ),
    ]
