# Generated by Django 4.2.29 on 2026-03-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_remove_revenue_target_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Einheit'),
        ),
    ]
