# Generated by Django 4.2.29 on 2026-03-26 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0044_project_team_lead_remove_limit_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='billing_type',
            field=models.CharField(choices=[('flat', 'Pauschal'), ('hourly', 'Stundenbasiert'), ('at_cost', 'Nach Nachweis'), ('commission', 'Provision')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='billing_type',
            field=models.CharField(choices=[('flat', 'Pauschal'), ('hourly', 'Stundenbasiert'), ('at_cost', 'Nach Nachweis'), ('commission', 'Provision')], default='flat', max_length=20, verbose_name='Abrechnungsart'),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='billing_type',
            field=models.CharField(choices=[('flat', 'Pauschal'), ('hourly', 'Stundenbasiert'), ('at_cost', 'Nach Nachweis'), ('commission', 'Provision')], default='flat', max_length=20, verbose_name='Abrechnungsart'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Kundenbetreuer'),
        ),
    ]
