# Generated by Django 4.2.29 on 2026-03-08 11:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_billable_default', models.BooleanField(default=True, verbose_name='Standardmäßig fakturierbar')),
                ('color_hex', models.CharField(blank=True, default='#6366f1', help_text="Für die spätere UI-Darstellung, z.B. '#6366f1'.", max_length=7, verbose_name='Farbe (Hex)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tätigkeitsart',
                'verbose_name_plural': 'Tätigkeitsarten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Datum')),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Mindestens 0,25 h (15 min), maximal 24 h.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('24.00'))], verbose_name='Dauer (Stunden)')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('description', models.TextField(verbose_name='Tätigkeit')),
                ('is_billable', models.BooleanField(default=True, help_text='Ob diese Stunden dem Kunden in Rechnung gestellt werden können.', verbose_name='Fakturierbar')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], default='draft', max_length=15, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprüft am')),
                ('review_note', models.TextField(blank=True, help_text='Pflichtfeld bei Ablehnung.', verbose_name='Prüfnotiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='worktrack.activitytype', verbose_name='Tätigkeitsart')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='crm.project', verbose_name='Projekt')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Geprüft von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Zeitbuchung',
                'verbose_name_plural': 'Zeitbuchungen',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntryBulkApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, verbose_name='Anmerkung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_approvals_made', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
                ('entries', models.ManyToManyField(related_name='bulk_approvals', to='worktrack.timeentry', verbose_name='Zeitbuchungen')),
            ],
            options={
                'verbose_name': 'Batch-Freigabe',
                'verbose_name_plural': 'Batch-Freigaben',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'date'], name='worktrack_t_user_id_cb746f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['project', 'status'], name='worktrack_t_project_b16f1a_idx'),
        ),
    ]
