# Generated by Django 4.2.29 on 2026-03-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('ag_ruecksprache', 'AG Rücksprache'), ('akquise', 'Akquise'), ('bearbeitung', 'Bearbeitung des Projekts'), ('besprechung', 'Besprechung'), ('erhebungen', 'Erhebungen'), ('mails_telefonate', 'Mails-Telefonate'), ('ortstermin', 'Ortstermin'), ('projektablage', 'Projektablage')], default='', max_length=30, verbose_name='Tätigkeitsart'),
        ),
    ]
