# Generated by Django 4.2.29 on 2026-03-26 09:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worktrack', '0002_alter_timeentry_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=Decimal('40.0'), max_digits=4, verbose_name='Soll-Stunden / Woche')),
                ('days_per_week', models.PositiveSmallIntegerField(default=5, verbose_name='Arbeitstage / Woche')),
                ('vacation_days_per_year', models.PositiveSmallIntegerField(default=30, verbose_name='Urlaubstage / Jahr')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Arbeitszeitmodell',
                'verbose_name_plural': 'Arbeitszeitmodelle',
            },
        ),
        migrations.CreateModel(
            name='WorkdayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Arbeitsbeginn')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Arbeitsende')),
                ('break_mins', models.PositiveSmallIntegerField(default=0, verbose_name='Pause (Minuten)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Notiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_logs', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Stempeluhr-Eintrag',
                'verbose_name_plural': 'Stempeluhr-Einträge',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VacationAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Jahr')),
                ('total_days', models.PositiveSmallIntegerField(default=30, verbose_name='Urlaubstage gesamt')),
                ('carry_over_days', models.PositiveSmallIntegerField(default=0, verbose_name='Übertrag aus Vorjahr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_allowances', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Urlaubskonto',
                'verbose_name_plural': 'Urlaubskonten',
                'ordering': ['-year', 'user__last_name'],
                'unique_together': {('user', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('absence_type', models.CharField(choices=[('vacation', 'Urlaub'), ('sick', 'Krankmeldung'), ('special', 'Sonderurlaub'), ('other', 'Sonstiges')], default='vacation', max_length=20, verbose_name='Art')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('status', models.CharField(choices=[('pending', 'Beantragt'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=15, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Abwesenheit',
                'verbose_name_plural': 'Abwesenheiten',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='worktrack_a_user_id_a91850_idx'), models.Index(fields=['status'], name='worktrack_a_status_2e7395_idx')],
            },
        ),
    ]
