# Generated by Django 4.2.29 on 2026-03-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrack', '0003_absence_workdaylog_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='track_overtime',
            field=models.BooleanField(default=True, help_text='Bei Vertrauensarbeitszeit deaktivieren.', verbose_name='Überstunden erfassen'),
        ),
    ]
