# Generated by Django 4.2.29 on 2026-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrack', '0004_workschedule_track_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='default_break_mins',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Standard-Pause (Minuten)'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='default_end_time',
            field=models.TimeField(blank=True, help_text='z.B. 16:00', null=True, verbose_name='Standard-Arbeitsende'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='default_start_time',
            field=models.TimeField(blank=True, help_text='z.B. 08:00 — ermöglicht Schnell-Erfassung ganzer Tage.', null=True, verbose_name='Standard-Arbeitsbeginn'),
        ),
    ]
