# Generated by Django 4.2.29 on 2026-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrack', '0005_workschedule_default_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('is_half_day', models.BooleanField(default=False, help_text='z.B. Heiligabend Nachmittag', verbose_name='Halber Tag')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Feiertage werden nicht angezeigt.', verbose_name='Aktiv')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Hinweis')),
            ],
            options={
                'verbose_name': 'Feiertag',
                'verbose_name_plural': 'Feiertage',
                'ordering': ['date'],
            },
        ),
    ]
