# Generated by Django 4.2.29 on 2026-03-27 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_billing_type'),
        ('worktrack', '0006_publicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='invoiced_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_time_entries', to='crm.invoice', verbose_name='Abgerechnet in Rechnung'),
        ),
    ]
